[2025-08-03 18:54:17,516: INFO: <ipython-input-1-e79efcea341f>: Logging has been set up successfully.]
[2025-08-05 11:30:01,476: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 11:30:01,481: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 11:30:01,484: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 11:30:01,487: INFO: common: created directory at: artifacts]
[2025-08-05 11:49:36,471: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 11:49:36,476: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 11:49:36,479: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 11:49:36,483: INFO: common: created directory at: artifacts]
[2025-08-05 11:50:39,234: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 11:50:39,237: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 11:50:39,240: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 11:50:39,242: INFO: common: created directory at: artifacts]
[2025-08-05 11:58:04,499: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 11:58:04,508: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 11:58:04,511: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 11:58:04,515: INFO: common: created directory at: artifacts]
[2025-08-05 12:02:17,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 12:02:17,771: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 12:02:17,773: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 12:02:17,775: INFO: common: created directory at: artifacts]
[2025-08-05 12:13:23,934: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 12:13:23,938: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 12:13:23,940: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 12:13:23,943: INFO: common: created directory at: artifacts]
[2025-08-05 12:13:23,944: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 12:13:28,270: INFO: 887910524: Dataset downloaded: artifacts/data_ingestion/teen_phone_addiction_dataset.zip]
[2025-08-05 16:44:45,031: INFO: main: Logging has been set up successfully.]
[2025-08-05 17:18:55,573: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:18:55,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:18:55,651: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:18:55,667: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:18:55,669: INFO: common: created directory at: artifacts]
[2025-08-05 17:18:55,671: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:18:55,672: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'dataset_download_url']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 15, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\config\configuration.py", line 24, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'dataset_download_url'
[2025-08-05 17:20:47,560: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:20:47,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:20:47,565: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:20:47,567: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:20:47,568: INFO: common: created directory at: artifacts]
[2025-08-05 17:20:47,568: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:20:47,569: ERROR: main: 'DataIngestion' object has no attribute 'download_dataset']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.download_dataset()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_dataset'
[2025-08-05 17:26:26,325: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:26:26,328: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:26:26,329: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:26:26,330: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:26:26,331: INFO: common: created directory at: artifacts]
[2025-08-05 17:26:26,332: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:26:26,333: ERROR: main: 'DataIngestion' object has no attribute 'download_dataset']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.download_dataset()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_dataset'
[2025-08-05 17:27:47,254: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:27:47,257: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:27:47,259: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:27:47,261: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:27:47,261: INFO: common: created directory at: artifacts]
[2025-08-05 17:27:47,262: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:27:47,263: ERROR: main: 'DataIngestion' object has no attribute 'dataset_download_url']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.dataset_download_url()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'dataset_download_url'
[2025-08-05 17:29:23,496: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:29:23,499: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:29:23,501: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:29:23,502: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:29:23,505: INFO: common: created directory at: artifacts]
[2025-08-05 17:29:23,506: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:29:23,507: ERROR: main: 'DataIngestion' object has no attribute 'dataset_download_url']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.dataset_download_url()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'dataset_download_url'
[2025-08-05 17:32:53,684: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:32:53,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:32:53,689: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:32:53,690: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:32:53,691: INFO: common: created directory at: artifacts]
[2025-08-05 17:32:53,692: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:32:53,692: ERROR: main: 'DataIngestionConfig' object has no attribute 'source_URL']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.download_file()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\components\data_ingestion.py", line 17, in download_file
    url=self.config.source_URL, filename=self.config.local_data_file
        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestionConfig' object has no attribute 'source_URL'
[2025-08-05 17:34:04,140: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:34:04,142: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:34:04,144: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:34:04,145: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:34:04,146: INFO: common: created directory at: artifacts]
[2025-08-05 17:34:04,148: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:34:04,148: ERROR: main: 'DataIngestion' object has no attribute 'download_dataset']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.download_dataset()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_dataset'
[2025-08-05 17:39:53,927: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:39:53,928: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:39:53,929: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:39:53,929: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:39:53,930: INFO: common: created directory at: artifacts]
[2025-08-05 17:39:53,930: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:39:53,930: ERROR: main: 'DataIngestion' object has no attribute 'download_dataset']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.download_dataset()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestion' object has no attribute 'download_dataset'
[2025-08-05 17:50:24,911: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:50:24,913: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:50:24,914: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:50:24,915: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:50:24,916: INFO: common: created directory at: artifacts]
[2025-08-05 17:50:24,916: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:50:24,917: ERROR: main: 'DataIngestionConfig' object has no attribute 'source_URL']
Traceback (most recent call last):
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\main.py", line 11, in <module>
    obj.main()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\pipeline\stage_01_ingestion_data.py", line 17, in main
    data_ingestion.download_dataset()
  File "C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\Teen_Phone_Addiction\src\Teen_Phone_Addiction\components\data_ingestion.py", line 17, in download_dataset
    url=self.config.source_URL, filename=self.config.local_data_file
        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestionConfig' object has no attribute 'source_URL'
[2025-08-05 17:51:05,559: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:51:05,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:51:05,561: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:51:05,562: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:51:05,562: INFO: common: created directory at: artifacts]
[2025-08-05 17:51:05,563: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:51:06,386: INFO: data_ingestion: artifacts/data_ingestion/teen_phone_addiction_dataset.zip download! with following info: 
Connection: close
Content-Length: 116825
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "4f32beba62fbd4350775c9f1cf24c3624e5438e95af93462fb82bdb3c030ef63"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C480:1FADD0:A69D82:BE4BDF:68921A59
Accept-Ranges: bytes
Date: Tue, 05 Aug 2025 14:51:05 GMT
Via: 1.1 varnish
X-Served-By: cache-fra-eddf8230126-FRA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1754405465.261626,VS0,VE148
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 61014e8a1674bc401f0c0a80a9bf2d3e55ec3a3b
Expires: Tue, 05 Aug 2025 14:56:05 GMT
Source-Age: 0

]
[2025-08-05 17:51:06,453: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage completed <<<<<<<<<<<<]
[2025-08-05 17:58:59,157: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<<<<]
[2025-08-05 17:58:59,158: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-05 17:58:59,159: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-05 17:58:59,159: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-05 17:58:59,160: INFO: common: created directory at: artifacts]
[2025-08-05 17:58:59,160: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-05 17:58:59,938: INFO: data_ingestion: artifacts/data_ingestion/teen_phone_addiction_dataset.zip download! with following info: 
Connection: close
Content-Length: 116825
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "4f32beba62fbd4350775c9f1cf24c3624e5438e95af93462fb82bdb3c030ef63"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C480:1FADD0:A69D82:BE4BDF:68921A59
Accept-Ranges: bytes
Date: Tue, 05 Aug 2025 14:58:58 GMT
Via: 1.1 varnish
X-Served-By: cache-fra-eddf8230061-FRA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1754405939.845576,VS0,VE114
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 0f5b8db9f48e087ead08c5bf1389ad51db68bd82
Expires: Tue, 05 Aug 2025 15:03:58 GMT
Source-Age: 0

]
[2025-08-05 17:58:59,983: INFO: main: >>>>>>>>>>>>> stage Data Ingestion stage completed <<<<<<<<<<<<]
